

== Datenmodell

[plantuml,erd,png]
----
@startuml
class Questionnaire
class Student
class Question
class Teacher
class Answer
class AnswerOptions
class Options
class Student
class Survey



Options "*" -right-> "1" Question
Question "*" -up-> "1" Questionnaire
Answer "1" -left-> "*" Question
Questionnaire "1" -right-> " *" Survey
Teacher "1" -down-> " *" Survey
AnswerOptions -up- Answer
Student "*" -left-> "1" Survey
Student "1" -right-> "*" Answer
Answer "*" -up-> "1" Survey


@enduml
----



== Gant

[plantuml,gantt,png]
----
@startgantt
[Prototype design] lasts 9 days
[Code prototype] lasts 5 days
[Code prototype] starts at [Prototype design]'s end
[JavaFx Project] lasts 3 days
[JavaFx Project] starts at [Prototype design]'s end
@endgantt
----


== Pflichtenheft Digitalisierten Feedbackbögen

 Version: 1.0
 Version Date: 15.01.2020
 Autoren:
 -	Rosalie Mandel
 -	Kelly Tran
 -	Sandy Tang


==== 1.	Beschreibung der Ausgangssituation

Augenblicklich benutzen wir in der Schule Feedbackbögen um Professoren unsere Ansicht vom Unterricht näher die zubringen. Dadurch werden die Einblicke der Schüler weitergeleitet, also zum Beispiel welche Aspekte des Unterrichts den Schülern gefallen und welche eventuell verbessert werden können.
Mit dem Ausfüllen und Auswerten von Feedbackbögen verbindet man oft lange Ausfüllzeiten und viel Arbeit bei der Auswertung vor allem da die meisten Feedbackbögen bisher schriftlich behandelt wurden, durch die Digitalisierung soll dieses jedoch behoben werden.
Demnach ist die Definition des Ausgangszustand die schriftliche Durchführung der Fragebögen.


==== 2.	Istzustand

Derzeit stehen zwar mehrere mögliche Arten für das Arbeiten mit Feedbackbögen zu Verfügung dennoch sind aufgrund spezifischer Ansichten die Auswahl dieser nicht passend, wenn die Anforderungen beachtete werden.
Weshalb dies einer der Gründe ist für die Entwicklung einer eigenen Lösung.




==== 3. Problemstellung

Falls ein Professor mehrere Klassen besitzt in den Feedbackbögen durchgeführt werden sollen kann das Auswerten und Erstellen sehr aufwendig werden, außerdem besteht bei der Auswertung der Umfragen durch den Professor dann keine hundertprozentige Chance auf Anonymität.



==== 4.	Aufgabenstellung
Unsere Aufgabe liegt darin, ein Programm zu entwickeln, indem die Feedbackbögen nicht mehr händisch ausgefüllt werden sollen sondern am Rechner durchgeführt werden.


===== 4.1.	Funktionale Anforderungen

Das fertige Programm sollte die von den Schülern eingegebenen Daten auswerten können und dazu noch passende Daigramme erstellen.



======  4.1.1. Anwendungsfalldiagramm (Use-Case-Diagram)
Um einen besseren Überblick über die Produktfunktionen zu bekommen wird in unserem Falle ein Use-Case-Diagram benutzt.

====== 4.1.2. Use-Case


[plantuml]

----
left to right direction
actor Lehrer
actor :Schüler:

rectangle {


    (Befragung erstellen) as (Use2)

    Schüler -- (Fragebogen ausfüllen)
    Lehrer -- (Befragung auswerten)
    Lehrer -- (Use2)

    (Tans generieren ) .> (Use2) : extends
}

----

===== 5.	Zielsetzung
Unser Ziel ist es das Auswerten von Feedbackbögen für die Benutzer so einfach wie möglich zu gestalten.

===== 6.	Mengengerüst

Derzeit befinden sich an unsere Schule rund xyz Klassen um das Fragebogensystem in diesen anwenden zu können muss unser Projekt in der Lage die Anzahl an Professoren, Schülern, sowie auch Fragen verwalten zu können.





= Projektauftrag: Rosalie Mandel

=== Projektbezeichnung
Digitalisierte Feedbackbögen

=== Projektauftraggeber
 • Herr Prof. Stütz
 • Herr Prof. Reder

=== Projekthintergrund
Mit dem Ausfüllen und Auswerten von Feedbackbögen verbindet man oft lange Ausfüllzeiten und viel Arbeit bei der Auswertung.
Um das Problem zu lösen, entwickeln wir ein Programm, indem die Feedbackbögen nicht mehr händisch ausgefüllt werden müssen sondern am Rechner.
Damit wird dem Lehrer/in einiges an Arbeit erspart, weil die eigegeben Information nicht händisch ausgewertet werden müssen, sondern im Programm verarbeitet werden und die Daten in Form eines Diagramms ausgegeben werden.

=== Projektergebnis
Die Fragebögen werden am Rechner beantwortet und die anonym eingegeben Information werden verarbeitet und den Lehrer gesendet.

=== Projektziel
Das Programm soll die Rückmeldung der Schüler an Lehrer leichter gestalten und Zeit und Aufwand sparen.

=== Projektbeschreibung
Dem Schüler werden Fragen gestellt und es werden Textfelder angegeben, in denen man seine eigene Meinung zum Unterricht des Lehrers und zum Lehrer selbst hineinschreiben soll. Nachdem Ausfüllen der Fragen, werden diese von dem Programm automatisch ausgewertet und dann werden die Daten in Form eines Diagramms ausgegeben.

=== Projektstart
21.Oktober 2019

=== Projektende
voraussichtlich Mai 2020

=== Projektressourcen
IntelliJ IDEA Ultimate
Vorlagen verschiedener Fragebögen

=== Projektrisiko
Ein Projektrisiko könnte sein, dass das Projekt aufgrund zeitlicher und inhaltlicher Probleme nicht vollständig abgeschlossen werden kann.

=== Meilensteine
• Das Wissen für das Umsetzen der Projektidee erlangen
• Fragebögen ausfüllen können
• Daten der Fragebögen verarbeiten und auswerten können
• Geeignete Benutzeroberfläche designen

=== Projektorganisation
• Mandel Rosalie
• Tran Kelly
• Tang Sandy

Es gibt keine spezifische Arbeitsaufteilung unter den 2 Beteiligten. Die Arbeit wird gemeinsam durchgeführt.
Die Aufgabe als Ansprechpartnerin für unser Projekt übernimmt Mandel Rosalie











= Projektantrag: Rosalie Mandel


    ITP 2019/20, Version 1.0
    Projekt-Auftraggeber: Herr Prof. Stütz
    Projekt-Bezeichnung: Face-Recognition


=== Zielgruppe:
Besucher am Tag der Offenen Tür

=== Sinn/Zeck:
Das Projekt dient dazu, den Besucherinnen und Besuchern am Tag der offenen Tür zu zeigen, welche Räume sie noch nicht besucht haben und kann so die Orientierung in unserer Schule erleichtern und den Aufenthalt angenehmer gestalten.

=== Projekthintergrund:
Am Eingang sollen Fotos von allen Besuchern gemacht werden und ihre Gesichtsmerkmale sollen einer ID-Nummer zugefügt und gespeichert werden.
Nun werden in jedem Raum Fotos von jedem Besucher gemacht und diese werden dann mit den gespeicherten Fotos verglichen. Wenn es eine Übereinstimmung mit einem gespeicherten Gesicht gibt, wird die Information über den Aufenthalt in diesem Raum gespeichert.
In jedem Stockwerk soll ein Tablet zur Verfügung stehen, auf dem man abrufen kann in welchen Räumen man schon war und wo nicht, indem wieder ein Foto gemacht wird und die gespeicherten Informationen zu diesem Gesicht ausgegeben werden.

=== Endergebnis:
Das Projekt soll am Tag der offenen Tür verwendbar sein und soll den Besucher die Orientierung in unserer Schule erleichtern.

